# Generated by Django 4.1.1 on 2022-10-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='timg',
            field=models.ImageField(upload_to='pic'),
        ),
    ]
