# Generated by Django 4.1.1 on 2022-10-21 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Background',
        ),
    ]
